version: '3.8'
services:
  cache:
    container_name: cache
    image: "redis:latest"
    ports:
      - "6379:6379"
    command: redis-server
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
