version: '3.8'
services:
  k3n-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '3333:3333'
    volumes:
      - ./src:/app/src
  cache:
    container_name: cache
    image: "redis:latest"
    ports:
      - "6379:6379"
    command: redis-server
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
