version: '3.3'
services:
  k3n-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    restart: always
    depends_on:
      - redis
    ports:
      - '3333:3333'
    volumes:
      - ./src:/app/src
    networks:
        - k3n
  redis:
    container_name: redis-k3n
    restart: always
    image: redis:5-buster
    command: redis-server
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
        - k3n
networks:
  k3n:
    driver: bridge