# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: K3N CI/CD Production

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: yarn

    - name: Lint the codebase
      run: yarn lint

    - name: Test our code
      run: yarn test

    - name: Build
      run: yarn build

    # - name: Login
    #   run: npx warp login --api-key=${{ secrets.SD_API_KEY }}

    # - name: Deploy
    #   run: npx warp deploy --project ${ORG_PROJECT} --env ${DEPLOY_ENV}
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
